/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './node_modules/flowbite/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      width: {
        170: '42.5rem',
        190: '48rem',
      },
      height: {
        160: '40rem',
        170: '42.5rem',
      },
      colors: {
        Framework: '#4F4F4F',
        Engine: '#2F4F4F',
        SaaS: '#FF4500',
        IaC: '#FFD700',
        Database: '#8B0000',
        'CI/CD': '#FF8C00',
        Library: '#006400',
        'Programming-Language': '#0000CD',
        'Version-Control': '#FF1493',
        Architecture: '#FF69B4',
        Virtualization: '#00BFFF',
        Runtime: '#00CED1',
        Validation: '#2E8B57',
        API: '#FFA07A',
        'Payment-Gateway': '#FF7F50',
        'Message-Broker': '#FF6347',
        Containerization: '#CD6090',
        IaaS: '#008B8B',
        Monitoring: '#00FF7F',
        Testing: '#2E8B57',
        Authentication: '#FF00FF',
        Tunneling: '#CDB5CD',
        Web: '#EEC900',
        Graphics: '#00CED1',
        Tools: '#CDAF95',
        BaaS: '#FFA07A',
        'Scripting-Language': '#CDCD00',
        Serialization: '#FF6347',
      },
    },
  },
  plugins: [require('flowbite/plugin')],
}
